### ISSUE TITLE
Subscribing to a service that doesn't exist yet fails

### ISSUE THREAD

**Issue by titanous** [flynn-archive/discoverd#10]
Subscribing to a service that doesn't exist results in this log message from discoverd:

``` text
Subscribe:  100: Key Not Found (get: /discover/services/example)
```

No subsequent service updates are received by the client.

My expectation is that this should "just work" instead of silently failing for the client.

**Comment by progrium** [comment]
Yeah, I found this and thought I made an issue for it.

On Thu, Nov 14, 2013 at 3:35 PM, Jonathan Rudenberg <
notifications@github.com> wrote:

> Subscribing to a service that doesn't exist results in this log message
> from discoverd:
> 
> Subscribe:  100: Key Not Found (get: /discover/services/example)
> 
> No subsequent service updates are received by the client.
> 
> My expectation is that this should "just work" instead of silently failing
> for the client.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/go-discover/issues/10
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by progrium** [comment]
This should be resolved since there is a passing test case for nonexistant services
