### ISSUE TITLE
Leader Election

### ISSUE THREAD

**Issue by titanous** [flynn-archive/discoverd#11]
Example use cases:
- Standby scheduler becomes active
- Oldest PostgreSQL standby becomes primary

**Comment by progrium** [comment]
Blocked on etcd exposing the index keys were created. Alternatively they could provide some kind of numeric incrementer like ZK ephemeral nodes, but I doubt that. Was told created indexes might be in master in about a week.

**Comment by progrium** [comment]
Now see #26
