### ISSUE TITLE
Update to etcd v0.2.0

### ISSUE THREAD

**Issue by titanous** [flynn-archive/discoverd#13]
go-etcd change some things and etcd silently broke stuff last time we tried it.

**Comment by heyLu** [comment]
[etcd@7cf01fb](https://github.com/coreos/go-etcd/tree/7cf01fb) still compiles if you want to try without fixing this.

**Comment by titanous** [comment]
Fixed by 5e35a34e3843b2517701c62ba98386975d9ee9be.
