### ISSUE TITLE
Does not actually include the host when sending a port-only registration

### ISSUE THREAD

**Issue by miracle2k** [flynn-archive/discoverd#30]
Somewhere in the flynn docs it says registering with a port only would make discoverd send it out with it's own ip, but this is not currently the case. 

I wasn't entirely sure how this would be implemented (post-process the event from etcd?), so I wanted to raise it first for now.

**Comment by titanous** [comment]
[`expandAddr`](https://github.com/flynn/discoverd/blob/ec866a2d60499d53b05a7f5059d0ca6d3f7be9ea/agent/server.go#L91) in `Register` is supposed to take care of this. Is it not working?

**Comment by progrium** [comment]
It assumes you have EXTERNAL_IP set. Perhaps if that's not set it should
use 0.0.0.0?

On Fri, Feb 7, 2014 at 12:17 PM, Jonathan Rudenberg <
notifications@github.com> wrote:

> expandAddrhttps://github.com/flynn/discoverd/blob/ec866a2d60499d53b05a7f5059d0ca6d3f7be9ea/agent/server.go#L91in
> Register is supposed to take care of this. Is it not working?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/discoverd/issues/30#issuecomment-34482893
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by progrium** [comment]
Er, 0.0.0.0 or even localhost would probably cause more problems as it's
not useful in most scenarios.

Maybe we should make EXTERNAL_IP into a required argument for starting discoverd?

**Comment by titanous** [comment]
Or error when calling `Register` with no address and no `EXTERNAL_IP` set.

**Comment by miracle2k** [comment]
EXTERNAL_IP must be the one, thanks.
