### ISSUE TITLE
Adding serf as a backend for discovered

### ISSUE THREAD

**Issue by seshendra** [flynn-archive/discoverd#36]
Would it be possible to use hasicorp/serf as a backend for the discovered api? I haven't gone through the code completely (I'm no Go expert) so requesting this feature.

**Comment by titanous** [comment]
Serf doesn't currently provide the consistency guarantees required for leader election. If they end up providing such guarantees, this is totally possible.

**Comment by ramarnat** [comment]
How about Consul?

**Comment by progrium** [comment]
Consul would be reasonable.

On Wed, May 7, 2014 at 10:01 AM, Rohit Amarnath notifications@github.comwrote:

> How about Consul?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/discoverd/issues/36#issuecomment-42438235
> .

## 

Jeff Lindsay
http://progrium.com
