### ISSUE TITLE
Handle loss of heartbeat

### ISSUE THREAD

**Issue by miracle2k** [flynn-archive/discoverd#37]
This is somewhat related to https://github.com/flynn/go-discoverd/issues/13, but its not the same.

I keep having trouble with discoverd - for some reason services are dropped from discovery at unpredictable times, which looks something like this in the logs:

```
{"log":"2014/03/09 14:42:33 Heartbeat: geumja:rethinkdb:web 172.17.0.7:8080\n","stream":"stderr","time":"2014-03-09T14:42:33.902056386Z"}
{"log":"2014/03/09 14:42:33 Heartbeat: geumja:rethinkdb:cluster 172.17.0.7:29015\n","stream":"stderr","time":"2014-03-09T14:42:33.907993657Z"}
{"log":"2014/03/09 14:42:33 Heartbeat: geumja:rethinkdb:driver 172.17.0.7:28015\n","stream":"stderr","time":"2014-03-09T14:42:33.913445727Z"}
{"log":"2014/03/09 14:42:33 Heartbeat: geumja:app 172.17.0.8:8000\n","stream":"stderr","time":"2014-03-09T14:42:33.95033948Z"}
{"log":"2014/03/09 14:42:45 rpc: writing response: use of closed network connection\n","stream":"stderr","time":"2014-03-09T14:42:45.096179752Z"}
{"log":"2014/03/09 14:42:45 rpc: writing response: use of closed network connection\n","stream":"stderr","time":"2014-03-09T14:42:45.0962231Z"}
{"log":"2014/03/09 14:42:45 rpc: writing response: use of closed network connection\n","stream":"stderr","time":"2014-03-09T14:42:45.097679024Z"}
{"log":"2014/03/09 14:42:45 Heartbeat: error: 100: Key not found (/discover/services/geumja:rethinkdb:web/172.17.0.7:8080) [1084062]\n","stream":"stderr","time":"2014-03-09T14:42:45.098004912Z"}
{"log":"2014/03/09 14:42:45 Heartbeat: error: 100: Key not found (/discover/services/geumja:app/172.17.0.8:8000) [1084062]\n","stream":"stderr","time":"2014-03-09T14:42:45.112473364Z"}
{"log":"2014/03/09 14:42:45 Heartbeat: error: 100: Key not found (/discover/services/shelf/172.17.0.5:8888) [1084062]\n","stream":"stderr","time":"2014-03-09T14:42:45.112635126Z"}
```

There seems to some correlation with CPU activity, it seems to happen a lot when starting other docker containers, for example. Since this is a VMware virtual machine, running on a slow disk, I assume the cause is to be found there. (Though "writing response: use of closed network connection" seems strange).

Regardless, if a client heartbeat causes an error because the service is not or no longer available, that should be dealt with somehow.

Returning an error to the client and asking it to reconnect is one option. However, I wonder if the "heartbeat" and the "register" couldn't be equivalent. The heartbeat already seems to have all the information except for attributes.

If it is't prohibitive to include the attributes in the heartbeat, they could be used to transparently re-register the service if a heartbeat comes in for an expired key.

**Comment by titanous** [comment]
Yeah, I just ran into this. I agree that it makes sense to heartbeat with the full data, and we should figure out if there is a bug that causes the premature disappearance.
