### ISSUE TITLE
[discussion] why discoverd server is needed

### ISSUE THREAD

**Issue by ilovenwd** [flynn-archive/discoverd#44]
The majority of code is going into discoverd client.
So maybe the discoverd server is not needed (client talks directly to backend like etcd).
We can wrap multiple backends in client side.
The advantage (at least for etcd backend) is that the client library don't need a rpcplus implementation so it is much easier to write (just http).
But I'm not sure what the situation is in the zookeeper backend case.
Unless rpcplus is a very popular protocol, the client only solution would be more simple and robust.

**Comment by progrium** [comment]
I've been thinking about this too. A standalone mode for the client that
just pulls in the server and talks to it directly might be a good idea. If
I were to do a "configd" for shared configuration, that's how I'd do it
now.

On Wed, May 7, 2014 at 9:34 AM, ilovenwd notifications@github.com wrote:

> The majority of code is going into discoverd client.
> So maybe the discoverd server is not needed (client talks directly to
> backend like etcd).
> We can wrap multiple backends in client side.
> The advantage (at least for etcd backend) is that the client library don't
> need a rpcplus implementation so it is much easiler to write (just http).
> But I'm not sure what the situation is in the zookeeper backend case.
> Unless rpcplus is a very popular protocol, the client only solution would
> be more simple and robust.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/discoverd/issues/44
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by titanous** [comment]
A standalone mode is doable without much work, but I'm in favor of using the daemon in production:
- It allows us to add strong auth{z,n} and encryption. If clients connect to the backend directly we have to push all of the security features there.
- We can reduce load on backends by only opening fewer streams and doing fanout in the daemon.
- It saves us from implementing and maintaining each backend protocol in every language.

Also, we won't be sticking with rpcplus in the long run, currently [duplex](https://github.com/progrium/duplex) is the frontrunner replacement option.

**Comment by titanous** [comment]
Another thing is that we'd need to push backend connection info to every service in the system instead of only discoverd.

**Comment by progrium** [comment]
In my latest prototypes, I'm using Consul directly and able to get roughly
the same functionality with less moving parts. In particular, I'm quite
happy doing service lookups via DNS SRV records on Consul.

The next release of Consul will have a fairly expressive leader election
API (better guarantees than what we have and what etcd'd module has). So
I'm really considering a minimal install that _doesn't_ include discoverd.
Just to let you guys know what I've been toying with trying to simplify
things. Starting to use the client in standalone mode now might be a path
towards this potential future where discoverd and its client are rarely
used at all. Though that said, Jonathan's concerns are totally valid, so
maybe it's not worth it yet.

On Wed, May 7, 2014 at 11:39 AM, Jonathan Rudenberg <
notifications@github.com> wrote:

> Another thing is that we'd need to push backend connection info to every
> service in the system instead of only discoverd.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/discoverd/issues/44#issuecomment-42451027
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by titanous** [comment]
@progrium do you have a link to the info about the new Consul API?

**Comment by progrium** [comment]
Hmmm, no it's in their google groups though. Lots of discussion around it.

On Wed, May 7, 2014 at 1:08 PM, Jonathan Rudenberg <notifications@github.com

> wrote:
> 
> @progrium https://github.com/progrium do you have a link to the info
> about the new Consul API?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/discoverd/issues/44#issuecomment-42461980
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by titanous** [comment]
@progrium is this the thread? https://groups.google.com/forum/#!searchin/consul-tool/election/consul-tool/E4kX_FdLUPI/8s96nPBk4VgJ

**Comment by progrium** [comment]
Yeah I think that's the main one. You want to chime in? I mostly talked
with Armon at Gophercon.

On Wed, May 7, 2014 at 1:36 PM, Jonathan Rudenberg <notifications@github.com

> wrote:
> 
> @progrium https://github.com/progrium is this the thread?
> https://groups.google.com/forum/#!searchin/consul-tool/election/consul-tool/E4kX_FdLUPI/8s96nPBk4VgJ
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/discoverd/issues/44#issuecomment-42465542
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by ilovenwd** [comment]
> It allows us to add strong auth{z,n} and encryption. If clients connect to the backend directly we have to push all of the security features there.

If a user decide to use a backend without security feature, we need not/shuld not implement that in the client lib. Most open source tools is just stick to ONE backend and do it well and flexible(so allows switch to other backend in the future if needed). 
Multi discoverd backend isn't really a good feature for flynn. Flynn is already very flexible, a user who need zookeeper can writer their own compatible discoverd client anyway.
I realy hope flynn can tick to just ONE(and the BEST) discovery system, 
leaving others to the ones who need it, but not in flynn core.

> We can reduce load on backends by only opening fewer streams and doing fanout in the daemon.

+1. This is also my major concern.

> It saves us from implementing and maintaining each backend protocol in every language.

Since popular backend like etcd has very good client libs, this should not be a big problem.
