### ISSUE TITLE
Add Consul as a backend

### ISSUE THREAD

**Issue by ramarnat** [flynn-archive/discoverd#45]
Opening this as an issue - better than the original serf option - #36

**Comment by ramarnat** [comment]
@progrium considering the work you are doing with docksul, will we be seeing this integration soon?

**Comment by progrium** [comment]
It would not be hard to add, but I just don't have time. I bet you could do it. :)

**Comment by ramarnat** [comment]
thats fair. :)

Have that dearth of time too, but will see what I can arrange.
