### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by miracle2k** [flynn-archive/discoverd#48]
I'm not using the latest version, but unless its been fixed, I think there is probably a memory leak here. This is discoverd after two weeks:

```
 PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
1901 root      20   0 16.2g 8.8g 2160 D   16 89.8 361:08.10 discoverd
```

If only we had duplex and I could just restart it without crashing every service!

**Comment by lmars** [comment]
I saw this recently too:

```
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                            
 2655 root      20   0  863m 355m  996 S 42.0 72.7   2:35.82 /bin/discoverd -bind=:1111 -etcd=http://172.17.0.3:4001                                            
```

I had to kill it as my vm had no memory left, but I think its reproducible by just leaving it to run for a few hours.

The high CPU usage is odd too.

**Comment by titanous** [comment]
The first step to debugging this will be to send a SIGQUIT to the process and grab the goroutine dump from the output. If it's a goroutine leak, the problem should be obvious. If not, we'll move on to a heap dump (added in Go 1.3).

**Comment by miracle2k** [comment]
This very much seems to be a goroutine leak, namely this one:

```
goroutine 281390 [chan receive]:
github.com/flynn/rpcplus.func·003()
    /var/folders/xm/c7hlfx_n1nbfk4xpt99s284m0000gn/T/godep/rev/05/df3d30b6e55f5b440c1a78e2f83cb822bc0d76/src/github.com/flynn/rpcplus/server.go:613 +0x4d
created by github.com/flynn/rpcplus.(*Server).ServeCodecWithContext
    /var/folders/xm/c7hlfx_n1nbfk4xpt99s284m0000gn/T/godep/rev/05/df3d30b6e55f5b440c1a78e2f83cb822bc0d76/src/github.com/flynn/rpcplus/server.go:617 +0x658
```

**Comment by titanous** [comment]
@jayd3e I pushed a new flynn/discoverd image that should fix this, would you test it out?

**Comment by jayd3e** [comment]
Yeah I can do that.  Will pull down the new image today, and test it over the next few days.
